volumes:
  postgres_volume:
  redis-data:

services:
  pg:
    image: postgres:14-alpine3.17
    container_name: pg-container
    env_file:
      - ".env"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    env_file:
      - ".env"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data